name: Issues
on:
  issues:
    types:
      - opened
      - closed
      - deleted
      - reopened

jobs:
  opened:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Details: ${{ github.event.issue.body }}"

  closed:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Details: ${{ github.event.issue.body }}"

  deleted:
    runs-on: ubuntu-latest
    if: github.event.action == 'deleted'
    steps:
      - run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Details: ${{ github.event.issue.body }}"

  reopened:
    runs-on: ubuntu-latest
    if: github.event.action == 'reopened'
    steps:
      - run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Details: ${{ github.event.issue.body }}"
