name: Issues
on:
  issues:
    types:
      - opened
      - closed
      - deleted
      - reopened

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Display Trigger event
        run: echo "${{ toJSON(github.event) }}"
